### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by xmunoz** [xmunoz/rubberband#1]
From @tkralphs

> Hey Cristina,
> 
> First of all, yay, it's running on my server at Lehigh :). I just looked over the whole thing quickly now and below are the issues I found so far. Keep in mind that we try to do these reviews as "dumb users." I was able to overcome all of these issues, but it would still be nice to improve the documentation if it can be done without much effort.
> 
> 1. For the section on installing elastic search, the instructions are specific to Ubuntu and probably won't work for most Debian or Fedora/CentOS installations. You don't necessarily need to have explicit instructions for those distros, but it would be good to indicate that what is needed is just to get java 8 installed and that instructions for that can be found by Googling. I was able to get instructions for installing java 8 on Debian pretty easily and that more or less enough to make it through getting elastic search installed.
> 
> 2. There seems to be a dependency on "click". I had to pip install "click" to get rubberband to run.
> 
> 3. You can't run "rubberband-ctl" before installing rubberband :), so the 
> 
> source venv/bin/activate
> pip install -e .
> 
> has to come before populating the database.
> 
> 4. The ipet dependency will fail for most users, since it's not on github. Is that necessary? I guess not, since everything seems to be OK without it. Some explanation of what role ipet plays in all of this and what can't be done without it would be good. Of course, ipet will hopfully be available publicly before long.
> 
> 5. For seeding the database, it might be nice to include some expected output or some indication of what should happen. 
> 
> 6. Same for tests.
> 
> After getting past the tests, I really didn't have much idea what to do next, so I just ran 
> 
> python server.py
> 
> and then was actually able to see something at
> 
> coral.ie.lehigh.edu:8888
> 
> Yay! You won't be able to do the same because the port is only open through our VPN (and I'm going to kill the server shortly). It seems as though there should be a bit more on actually starting the server and maybe some screenshots of what one should see.
> 
> More later when I start trying to upload things, etc.
> 
> Ted

**Comment by xmunoz** [comment]
> For the section on installing elastic search, the instructions are specific to Ubuntu and probably won't work for most Debian or Fedora/CentOS installations.

Yes, I agree that this section is both very ubuntu specific and also unnecessary. When I wrote it, I was writing documentation for the not-very-tech-saavy users at ZIB, where only Ubuntu is installed. For the average technical person however, googling should be sufficient and this section can, and will, be removed.

> There seems to be a dependency on "click". I had to pip install "click" to get rubberband to run.

The instructions for a "dev" environment setup tell the user to install requirements from `requirements-dev.txt`. This includes`click`, as well as other development requirements. I should probably add `click` to the regular `requirements.txt` though, since a regular production deployment will at least need to create the schema.

> You can't run "rubberband-ctl" before installing rubberband :), so the

Da hast du recht. Will fix.

> The ipet dependency will fail for most users,

[No it won't](https://pypi.python.org/pypi/ipet_reader/0.0.10). I don't know what Gregor intends to do with IPET, but since he has assigned it an MIT license, I've open-sourced my fork in order to make Rubberband functional now, for travis-ci and for you :)
https://github.com/xmunoz/ipet-reader

> For seeding the database, it might be nice to include some expected output or some indication of what should happen.
> Same for tests.

Let me think about the best way to do that.

**Comment by tkralphs** [comment]
>> For the section on installing elastic search, the instructions are specific to Ubuntu and probably won't work for most Debian or Fedora/CentOS installations.

> Yes, I agree that this section is both very ubuntu specific and also unnecessary. When I wrote it, I was writing documentation for the not-very-tech-saavy users at ZIB, where only Ubuntu is installed. For the average technical person however, googling should be sufficient and this section can, and will, be removed.

Why do you think it should be removed? It's definitely an important step, right? But you can just say that one needs to install Java 8 as appropriate on your distro. And having a list of distros on which it is know that all of this can be installed successfully would be good. 

> >There seems to be a dependency on "click". I had to pip install "click" to get rubberband to run.

> The instructions for a "dev" environment setup tell the user to install requirements from requirements-dev.txt. This includesclick, as well as other development requirements. I should probably add click to the regular requirements.txt though, since a regular production deployment will at least need to create the schema.

OK, yes, those were the instructions, but I guess I don't understand the use case in which one would do anything other than install those requirements. 
 
>> The ipet dependency will fail for most users,

> No it won't. I don't know what Gregor intends to do with IPET, but since he has assigned it an MIT license, I've open-sourced my fork in order to make Rubberband functional now, for travis-ci and for you :)
> https://github.com/xmunoz/ipet-reader

OK, I guess I was referring to `setup.py` having a reference to the ZIB gitlab repo. This results in
```
    Not found: git+git@git.zib.de:optimization/ipet-reader.git#egg=ipet-reader
```
when installing.

**Comment by xmunoz** [comment]
Once you accept my collaborator invitation, I can assign the open Pull Request to you for review.
